const { CanonicalAuthority } = require('./canonical_authority');
const { constitutionalTimeAuthority } = require('./constitutional_time_authority');
const { witnessAuthority } = require('./witness_authority');

/**
 * Performance Baseline Witness
 * 
 * Phase 2.5 — Performance Baseline Witness
 * 
 * Performance isn't constitutional, but regressions are valuable to detect.
 * 
 * Records telemetry:
 * - generation_time_ms
 * - compile_time_ms
 * - replay_time_ms
 * - peak_memory_bytes
 * - artifact_size_bytes
 * - generator_cpu_time
 * - serializer_time
 * 
 * These are treated as telemetry, not approval criteria.
 */

class PerformanceBaselineWitness {
  constructor() {
    this._performanceBaselines = new Map();
    this._currentMetrics = {};
  }

  /**
   * Start measuring generation time
   */
  startGenerationTimer() {
    this._currentMetrics.generation_start = constitutionalTimeAuthority.now();
  }

  /**
   * Stop measuring generation time
   */
  stopGenerationTimer() {
    if (this._currentMetrics.generation_start) {
      this._currentMetrics.generation_time_ms = constitutionalTimeAuthority.now() - this._currentMetrics.generation_start;
      delete this._currentMetrics.generation_start;
    }
  }

  /**
   * Start measuring compile time
   */
  startCompileTimer() {
    this._currentMetrics.compile_start = constitutionalTimeAuthority.now();
  }

  /**
   * Stop measuring compile time
   */
  stopCompileTimer() {
    if (this._currentMetrics.compile_start) {
      this._currentMetrics.compile_time_ms = constitutionalTimeAuthority.now() - this._currentMetrics.compile_start;
      delete this._currentMetrics.compile_start;
    }
  }

  /**
   * Start measuring replay time
   */
  startReplayTimer() {
    this._currentMetrics.replay_start = constitutionalTimeAuthority.now();
  }

  /**
   * Stop measuring replay time
   */
  stopReplayTimer() {
    if (this._currentMetrics.replay_start) {
      this._currentMetrics.replay_time_ms = constitutionalTimeAuthority.now() - this._currentMetrics.replay_start;
      delete this._currentMetrics.replay_start;
    }
  }

  /**
   * Start measuring serializer time
   */
  startSerializerTimer() {
    this._currentMetrics.serializer_start = constitutionalTimeAuthority.now();
  }

  /**
   * Stop measuring serializer time
   */
  stopSerializerTimer() {
    if (this._currentMetrics.serializer_start) {
      this._currentMetrics.serializer_time = constitutionalTimeAuthority.now() - this._currentMetrics.serializer_start;
      delete this._currentMetrics.serializer_start;
    }
  }

  /**
   * Record peak memory usage
   * @param {number} bytes - Peak memory in bytes
   */
  recordPeakMemory(bytes) {
    this._currentMetrics.peak_memory_bytes = bytes;
  }

  /**
   * Record artifact size
   * @param {number} bytes - Artifact size in bytes
   */
  recordArtifactSize(bytes) {
    this._currentMetrics.artifact_size_bytes = bytes;
  }

  /**
   * Record generator CPU time
   * @param {number} ms - CPU time in milliseconds
   */
  recordGeneratorCpuTime(ms) {
    this._currentMetrics.generator_cpu_time = ms;
  }

  /**
   * Create performance baseline witness
   * @param {string} artifactId - Artifact ID
   * @returns {Object} Performance baseline witness
   */
  createPerformanceBaseline(artifactId) {
    const witnessData = {
      artifact_id: artifactId,
      generation_time_ms: this._currentMetrics.generation_time_ms || 0,
      compile_time_ms: this._currentMetrics.compile_time_ms || 0,
      replay_time_ms: this._currentMetrics.replay_time_ms || 0,
      peak_memory_bytes: this._currentMetrics.peak_memory_bytes || 0,
      artifact_size_bytes: this._currentMetrics.artifact_size_bytes || 0,
      generator_cpu_time: this._currentMetrics.generator_cpu_time || 0,
      serializer_time: this._currentMetrics.serializer_time || 0,
    };

    const witness = witnessAuthority.createWitness(witnessData, {
      authority: 'PerformanceBaselineWitness',
      authority_version: '1.0.0'
    });
    
    this._performanceBaselines.set(witness.witness_id, witness);

    // Reset current metrics
    this._currentMetrics = {};

    return witness;
  }

  /**
   * Get performance baseline for artifact
   * @param {string} artifactId - Artifact ID
   * @returns {Object} Performance baseline witness
   */
  getPerformanceBaseline(artifactId) {
    // Since witness IDs are now generated by witnessAuthority, we need to search by artifact_id
    for (const [witnessId, witness] of this._performanceBaselines) {
      if (witness.artifact_id === artifactId) {
        return witness;
      }
    }
    return null;
  }

  /**
   * Compare performance against baseline
   * @param {string} artifactId - Artifact ID
   * @param {Object} currentMetrics - Current metrics
   * @returns {Object} Performance comparison result
   */
  comparePerformance(artifactId, currentMetrics) {
    const baseline = this.getPerformanceBaseline(artifactId);

    if (!baseline) {
      return {
        has_baseline: false,
        message: 'No baseline found for comparison'
      };
    }

    const comparison = {
      has_baseline: true,
      generation_time_delta: currentMetrics.generation_time_ms - baseline.generation_time_ms,
      compile_time_delta: currentMetrics.compile_time_ms - baseline.compile_time_ms,
      replay_time_delta: currentMetrics.replay_time_ms - baseline.replay_time_ms,
      peak_memory_delta: currentMetrics.peak_memory_bytes - baseline.peak_memory_bytes,
      artifact_size_delta: currentMetrics.artifact_size_bytes - baseline.artifact_size_bytes,
      generator_cpu_delta: currentMetrics.generator_cpu_time - baseline.generator_cpu_time,
      serializer_time_delta: currentMetrics.serializer_time - baseline.serializer_time
    };

    // Detect regressions (more than 20% increase)
    const regressions = [];
    const regressionThreshold = 0.2;

    if (comparison.generation_time_delta > baseline.generation_time_ms * regressionThreshold) {
      regressions.push('generation_time');
    }
    if (comparison.compile_time_delta > baseline.compile_time_ms * regressionThreshold) {
      regressions.push('compile_time');
    }
    if (comparison.replay_time_delta > baseline.replay_time_ms * regressionThreshold) {
      regressions.push('replay_time');
    }
    if (comparison.peak_memory_delta > baseline.peak_memory_bytes * regressionThreshold) {
      regressions.push('peak_memory');
    }
    if (comparison.artifact_size_delta > baseline.artifact_size_bytes * regressionThreshold) {
      regressions.push('artifact_size');
    }

    comparison.has_regressions = regressions.length > 0;
    comparison.regressions = regressions;

    return comparison;
  }

  /**
   * Clear all baselines (for testing)
   */
  clear() {
    this._performanceBaselines.clear();
    this._currentMetrics = {};
  }

  /**
   * Get all performance baselines
   * @returns {Array} Array of performance baselines
   */
  getAllBaselines() {
    return Array.from(this._performanceBaselines.values());
  }
}

module.exports = { PerformanceBaselineWitness };
