#!/usr/bin/env python3
"""
Secure Random Secret Generation Script
Generates cryptographically secure random secrets for all required environment variables
"""

import secrets
import string
import sys
from pathlib import Path

def generate_password(length=32, use_special=True):
    """Generate cryptographically secure random password."""
    alphabet = string.ascii_letters + string.digits
    if use_special:
        alphabet += "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def generate_api_key(length=64):
    """Generate cryptographically secure random API key."""
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def generate_jwt_secret(length=64):
    """Generate cryptographically secure random JWT secret."""
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def generate_encryption_key(length=32):
    """Generate cryptographically secure random encryption key."""
    return secrets.token_hex(length)

def generate_env_file():
    """Generate .env file with secure random secrets."""
    secrets_dict = {
        # PostgreSQL
        'POSTGRES_USER': 'brain_user',
        'POSTGRES_PASSWORD': generate_password(32),
        'POSTGRES_DB': 'brain_db',
        
        # Qdrant
        'QDRANT_API_KEY': generate_api_key(64),
        
        # Neo4j
        'NEO4J_PASSWORD': generate_password(32),
        
        # Temporal
        'TEMPORAL_HOST': 'temporal',
        'TEMPORAL_NAMESPACE': 'default',
        
        # Kafka
        'KAFKA_BROKER': 'kafka:9092',
        
        # OpenSearch
        'OPENSEARCH_PASSWORD': generate_password(32),
        
        # Security
        'JWT_SECRET': generate_jwt_secret(64),
        'ENCRYPTION_MASTER_KEY': generate_encryption_key(32),
        'BACKUP_ENCRYPTION_KEY': generate_encryption_key(32),
        
        # Storage Paths
        'OBJECT_STORE_ROOT': '/storage/objects',
        'EVENT_LOG_ROOT': '/storage/events',
        'CANONICAL_DB_ROOT': '/storage/canonical',
        'VECTOR_STORAGE_PATH': '/storage/vectors',
        'GRAPH_STORAGE_PATH': '/storage/graph',
        'MEMORY_STORAGE_PATH': '/storage/memory',
        
        # Service Hosts
        'OLLAMA_HOST': 'http://ollama:11434',
        'OPENWEBUI_HOST': 'http://openwebui:8080',
        'TIKA_HOST': 'http://tika:9998',
        
        # Logging
        'LOG_LEVEL': 'info',
        
        # Vaultwarden
        'VAULTWARDEN_ADMIN_TOKEN': generate_api_key(64),
        
        # Backup Configuration
        'BACKUP_RETENTION_DAYS': '90',
        'BACKUP_SCHEDULE': '0 2 * * *',
        'BACKUP_COMPRESSION': 'true',
        'BACKUP_ENCRYPTION': 'true',
        
        # Network Configuration
        'INTERNAL_NETWORK': 'brain_internal',
        'EXTERNAL_NETWORK': 'brain_external',
        
        # Monitoring
        'METRICS_ENABLED': 'true',
        'METRICS_PORT': '9090',
        'HEALTH_CHECK_INTERVAL': '30s',
        
        # Development
        'DEBUG': 'false',
        'DEV_MODE': 'false',
    }
    
    # Write to .env file
    env_path = Path(__file__).parent.parent.parent.parent / 'config' / 'environments' / '.env'
    
    with open(env_path, 'w') as f:
        f.write("# Brain Constitutional Infrastructure - Environment Configuration\n")
        f.write("# Generated by generate_secrets.py\n")
        f.write("# DO NOT COMMIT THIS FILE\n")
        f.write("# DO NOT SHARE THIS FILE\n")
        f.write("\n")
        
        for key, value in secrets_dict.items():
            f.write(f"{key}={value}\n")
    
    print(f"Generated secure secrets at: {env_path}")
    print("\nIMPORTANT:")
    print("1. Store this file securely")
    print("2. Do not commit to version control")
    print("3. Do not share with unauthorized personnel")
    print("4. Backup this file to a secure location")
    print("5. Rotate secrets regularly")

def generate_secrets_backup():
    """Generate encrypted backup of secrets."""
    import json
    from cryptography.fernet import Fernet
    
    # Generate encryption key
    key = Fernet.generate_key()
    cipher = Fernet(key)
    
    # Read .env file
    env_path = Path(__file__).parent.parent.parent.parent / 'config' / 'environments' / '.env'
    
    with open(env_path, 'r') as f:
        env_content = f.read()
    
    # Encrypt
    encrypted = cipher.encrypt(env_content.encode())
    
    # Save encrypted backup
    backup_path = Path(__file__).parent.parent.parent.parent / 'config' / 'environments' / '.env.backup.enc'
    
    with open(backup_path, 'wb') as f:
        f.write(encrypted)
    
    # Save encryption key separately
    key_path = Path(__file__).parent.parent.parent.parent / 'config' / 'environments' / '.env.key'
    
    with open(key_path, 'wb') as f:
        f.write(key)
    
    print(f"Encrypted backup saved to: {backup_path}")
    print(f"Encryption key saved to: {key_path}")
    print("\nIMPORTANT:")
    print("1. Store the encryption key separately from the backup")
    print("2. Do not commit either file to version control")
    print("3. Store both files in secure locations")

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--backup':
        generate_secrets_backup()
    else:
        generate_env_file()
