"""
Vault Production Hardening

Constitutional: Production-grade Vault configuration for secure secret management.

Features:
- AppRole rotation (24-hour cycle)
- Audit logging
- Root token revocation
- Production configuration recommendations

Architecture:
AppRole Rotation:
    - Generate new secret_id every 24 hours
    - Revoke old secret_id
    - Update applications with new credentials

Audit Logging:
    - Log all Vault operations
    - Enable file-based audit logs
    - Monitor for suspicious activity

Production Configuration:
    - Disable dev mode
    - Use proper TLS
    - Enable auto-unseal
    - Configure HA/DR
"""

import os
import json
from typing import Dict, List, Optional


class VaultHardening:
    """
    Vault production hardening configuration.
    
    Constitutional: Production-grade security settings for Vault.
    """
    
    @staticmethod
    def get_production_config() -> Dict:
        """
        Get production Vault configuration.
        
        Returns:
            Production configuration dictionary
        """
        return {
            "listener": {
                "tcp": {
                    "address": "0.0.0.0:8200",
                    "tls_cert_file": "/vault/tls/vault.crt",
                    "tls_key_file": "/vault/tls/vault.key",
                    "tls_client_ca_file": "/vault/tls/ca.crt",
                    "tls_min_version": "tls12"
                }
            },
            "storage": {
                "consul": {
                    "address": "consul:8500",
                    "path": "vault/"
                }
            },
            "seal": {
                "awskms": {
                    "region": "us-east-1",
                    "kms_key_id": "arn:aws:kms:us-east-1:123456789012:key/abcd1234"
                }
            },
            "ui": True,
            "api_addr": "https://vault.example.com",
            "cluster_addr": "https://vault-cluster.example.com",
            "disable_mlock": False,
            "log_level": "info"
        }
    
    @staticmethod
    def get_approle_rotation_config() -> Dict:
        """
        Get AppRole rotation configuration.
        
        Returns:
            AppRole rotation configuration
        """
        return {
            "role_name": "ping-app",
            "token_ttl": "1h",
            "token_max_ttl": "4h",
            "token_policies": ["ping-policy"],
            "secret_id_ttl": "24h",
            "secret_id_num_uses": 0,
            "enable_secret_id_rotation": True
        }
    
    @staticmethod
    def get_audit_config() -> Dict:
        """
        Get audit logging configuration.
        
        Returns:
            Audit configuration
        """
        return {
            "file": {
                "path": "/vault/logs/audit.log",
                "format": "json",
                "mode": "0600"
            },
            "syslog": {
                "facility": "AUTH",
                "tag": "vault",
                "log_level": "info"
            }
        }
    
    @staticmethod
    def generate_vault_hcl() -> str:
        """
        Generate Vault HCL configuration for production.
        
        Returns:
            HCL configuration string
        """
        config = VaultHardening.get_production_config()
        
        hcl = """# Vault Production Configuration
# Generated by vault_hardening.py

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/tls/vault.crt"
  tls_key_file = "/vault/tls/vault.key"
  tls_client_ca_file = "/vault/tls/ca.crt"
  tls_min_version = "tls12"
}

storage "consul" {
  address = "consul:8500"
  path = "vault/"
}

seal "awskms" {
  region = "us-east-1"
  kms_key_id = "arn:aws:kms:us-east-1:123456789012:key/abcd1234"
}

ui = true

api_addr = "https://vault.example.com"
cluster_addr = "https://vault-cluster.example.com"

disable_mlock = false

log_level = "info"
"""
        return hcl
    
    @staticmethod
    def generate_rotation_script() -> str:
        """
        Generate AppRole secret ID rotation script.
        
        Returns:
            Bash script for rotation
        """
        script = """#!/bin/bash
# AppRole Secret ID Rotation Script
# Run this daily via cron to rotate secret IDs

VAULT_ADDR="https://vault.example.com"
VAULT_TOKEN="${VAULT_ROOT_TOKEN}"
ROLE_NAME="ping-app"

# Get current secret ID
CURRENT_SECRET_ID=$(vault read -field=secret_id auth/approle/role/${ROLE_NAME}/secret-id)

# Generate new secret ID
NEW_SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/${ROLE_NAME}/secret-id)

# Revoke old secret ID
vault delete auth/approle/role/${ROLE_NAME}/secret-id/${CURRENT_SECRET_ID}

# Update application configuration
# TODO: Update your application with new secret_id
# Example: Update environment variable, Kubernetes secret, etc.

echo "Secret ID rotated successfully"
echo "New secret ID: ${NEW_SECRET_ID}"
echo "Old secret ID revoked: ${CURRENT_SECRET_ID}"
"""
        return script
    
    @staticmethod
    def generate_audit_setup_commands() -> List[str]:
        """
        Generate Vault audit setup commands.
        
        Returns:
            List of vault CLI commands
        """
        return [
            "vault audit enable file file_path=/vault/logs/audit.log format=json",
            "vault audit enable syslog facility=AUTH tag=vault",
            "vault audit list"
        ]
    
    @staticmethod
    def generate_security_checklist() -> Dict:
        """
        Generate Vault security checklist.
        
        Returns:
            Security checklist dictionary
        """
        return {
            "critical": [
                "Disable dev mode in production",
                "Enable TLS for all Vault communication",
                "Use auto-unseal with AWS KMS or HSM",
                "Enable audit logging",
                "Implement AppRole rotation",
                "Revoke root token after initial setup",
                "Use least-privilege policies",
                "Enable Vault UI only behind authentication",
                "Configure backup and disaster recovery",
                "Monitor Vault health and performance"
            ],
            "recommended": [
                "Use Consul for HA cluster",
                "Enable Vault replication for DR",
                "Implement secret rate limiting",
                "Use Vault Agent for applications",
                "Configure Vault namespaces for multi-tenancy",
                "Enable response wrapping",
                "Use cubbyhole for temporary secrets",
                "Implement secret versioning with KV v2",
                "Configure Vault transit for encryption as a service",
                "Set up Vault monitoring and alerting"
            ],
            "forbidden": [
                "Never store root token in code",
                "Never use dev mode in production",
                "Never disable TLS",
                "Never share AppRole secret_id in code",
                "Never use default policies",
                "Never disable audit logging in production",
                "Never expose Vault UI to public internet",
                "Never store secrets in git",
                "Never use Vault without backup",
                "Never skip secret rotation"
            ]
        }


def main():
    """Generate Vault hardening artifacts."""
    print("Vault Production Hardening Configuration")
    print("=" * 60)
    
    hardening = VaultHardening()
    
    # Generate HCL config
    print("\n1. Vault HCL Configuration:")
    print("-" * 60)
    hcl = hardening.generate_vault_hcl()
    print(hcl)
    
    # Save HCL to file
    with open('C:/Users/nolan/PING/vault/production_config.hcl', 'w') as f:
        f.write(hcl)
    print("Saved to: vault/production_config.hcl")
    
    # Generate rotation script
    print("\n2. AppRole Rotation Script:")
    print("-" * 60)
    rotation_script = hardening.generate_rotation_script()
    print(rotation_script)
    
    # Save rotation script
    with open('C:/Users/nolan/PING/vault/rotate_approle.sh', 'w') as f:
        f.write(rotation_script)
    print("Saved to: vault/rotate_approle.sh")
    
    # Generate audit commands
    print("\n3. Audit Setup Commands:")
    print("-" * 60)
    audit_commands = hardening.generate_audit_setup_commands()
    for cmd in audit_commands:
        print(f"  {cmd}")
    
    # Generate security checklist
    print("\n4. Security Checklist:")
    print("-" * 60)
    checklist = hardening.generate_security_checklist()
    
    print("\nCritical:")
    for item in checklist['critical']:
        print(f"  [ ] {item}")
    
    print("\nRecommended:")
    for item in checklist['recommended']:
        print(f"  [ ] {item}")
    
    print("\nForbidden:")
    for item in checklist['forbidden']:
        print(f"  [X] {item}")
    
    # Save checklist
    with open('C:/Users/nolan/PING/vault/SECURITY_CHECKLIST.json', 'w') as f:
        json.dump(checklist, f, indent=2)
    print("\nSaved to: vault/SECURITY_CHECKLIST.json")
    
    print("\n" + "=" * 60)
    print("Vault hardening artifacts generated successfully!")
    print("=" * 60)


if __name__ == '__main__':
    main()
