# Vault Production Configuration
# Generated by vault_hardening.py

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/tls/vault.crt"
  tls_key_file = "/vault/tls/vault.key"
  tls_client_ca_file = "/vault/tls/ca.crt"
  tls_min_version = "tls12"
}

storage "consul" {
  address = "consul:8500"
  path = "vault/"
}

seal "awskms" {
  region = "us-east-1"
  kms_key_id = "arn:aws:kms:us-east-1:123456789012:key/abcd1234"
}

ui = true

api_addr = "https://vault.example.com"
cluster_addr = "https://vault-cluster.example.com"

disable_mlock = false

log_level = "info"
