import os
import sqlite3
from datetime import datetime
from collections import Counter

DATABASE_PATH = "newsletters.db"

def get_newsletters_for_date(date: str):
    """Get all processed newsletters for a specific date."""
    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()
    
    start_date = f"{date}T00:00:00"
    end_date = f"{date}T23:59:59"
    
    cursor.execute("""
        SELECT id, subject, sender, summary, key_ideas, actionable_insights, received_at
        FROM newsletters
        WHERE processed_at >= ? AND processed_at <= ?
        ORDER BY processed_at DESC
    """, (start_date, end_date))
    
    results = []
    for row in cursor.fetchall():
        results.append({
            'id': row[0],
            'subject': row[1],
            'sender': row[2],
            'summary': row[3],
            'key_ideas': row[4],
            'actionable_insights': row[5],
            'received_at': row[6]
        })
    
    conn.close()
    return results

def get_topics_for_newsletters(newsletter_ids):
    """Get all topics for a list of newsletter IDs."""
    if not newsletter_ids:
        return []
    
    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()
    
    placeholders = ','.join('?' * len(newsletter_ids))
    cursor.execute(f"""
        SELECT topic, COUNT(*) as count
        FROM newsletter_topics
        WHERE article_id IN ({placeholders})
        GROUP BY topic
        ORDER BY count DESC
    """, newsletter_ids)
    
    results = []
    for row in cursor.fetchall():
        results.append({
            'topic': row[0],
            'count': row[1]
        })
    
    conn.close()
    return results

def generate_daily_digest(date: str = None) -> str:
    """Generate daily intelligence brief from stored newsletter summaries."""
    if not date:
        date = datetime.utcnow().strftime('%Y-%m-%d')
    
    # Get newsletters for the day
    newsletters = get_newsletters_for_date(date)
    
    if not newsletters:
        return f"# Daily Intelligence Brief - {date}\n\nNo newsletters processed today."
    
    # Get newsletter IDs
    newsletter_ids = [n['id'] for n in newsletters]
    
    # Get topics
    topics = get_topics_for_newsletters(newsletter_ids)
    
    # Extract top themes
    top_themes = [t['topic'] for t in topics[:5]]
    
    # Extract all key ideas
    all_key_ideas = []
    for n in newsletters:
        if n['key_ideas']:
            ideas = n['key_ideas'].split('\n')
            all_key_ideas.extend([i.strip('- ').strip() for i in ideas if i.strip()])
    
    # Extract all actionable insights
    all_insights = []
    for n in newsletters:
        if n['actionable_insights']:
            insights = n['actionable_insights'].split('\n')
            all_insights.extend([i.strip('- ').strip() for i in insights if i.strip()])
    
    # Generate digest content
    digest = f"""# Daily Intelligence Brief

**Date:** {date}
**Articles Processed:** {len(newsletters)}
**Top Themes:** {', '.join(top_themes) if top_themes else 'None'}

---

## Top Themes

"""
    
    for theme in top_themes:
        digest += f"* {theme}\n"
    
    digest += "\n"
    
    # Most Important Articles
    digest += "## Most Important Articles\n\n"
    
    for i, newsletter in enumerate(newsletters[:5], 1):
        digest += f"### {i}. {newsletter['subject']}\n"
        digest += f"**From:** {newsletter['sender']}\n\n"
        digest += f"{newsletter['summary']}\n\n"
        
        if newsletter['key_ideas']:
            digest += "**Key Ideas:**\n"
            for idea in newsletter['key_ideas'].split('\n'):
                if idea.strip():
                    digest += f"{idea}\n"
            digest += "\n"
    
    # Consensus (common themes across articles)
    digest += "## Consensus\n\n"
    if len(top_themes) > 1:
        digest += f"The following themes appear consistently across today's newsletters:\n"
        for theme in top_themes[:3]:
            digest += f"- **{theme}**: Mentioned in multiple sources\n"
    else:
        digest += "Insufficient data to identify consensus themes.\n"
    
    digest += "\n"
    
    # Disagreements (would require more sophisticated analysis)
    digest += "## Disagreements\n\n"
    digest += "Disagreement analysis requires more sources and sentiment analysis.\n"
    digest += "This feature will be enhanced in future versions.\n\n"
    
    # Actionable Insights
    digest += "## Actionable Insights\n\n"
    
    if all_insights:
        for insight in all_insights[:10]:
            digest += f"* {insight}\n"
    else:
        digest += "No actionable insights extracted today.\n"
    
    digest += "\n"
    digest += "---\n"
    digest += f"*Generated by CRX Newsletter Brain on {datetime.utcnow().isoformat()}*\n"
    
    return digest

def save_daily_digest(date: str = None) -> str:
    """Generate and save daily digest to file."""
    if not date:
        date = datetime.utcnow().strftime('%Y-%m-%d')
    
    digest_content = generate_daily_digest(date)
    
    # Create digests directory
    digest_dir = os.path.join("knowledge", "digests")
    os.makedirs(digest_dir, exist_ok=True)
    
    # Save to file
    digest_file = os.path.join(digest_dir, f"daily-{date}.md")
    with open(digest_file, 'w', encoding='utf-8') as f:
        f.write(digest_content)
    
    return digest_file

if __name__ == "__main__":
    import sys
    
    date = sys.argv[1] if len(sys.argv) > 1 else None
    
    digest = generate_daily_digest(date)
    print(digest)
    
    file_path = save_daily_digest(date)
    print(f"\n✓ Digest saved to: {file_path}")
