"""
Evidence Engine - Evidence Compiler.

Input: Mission
Output: Evidence Plan

Example:
Mission requires:
- compile
- unit tests
- integration tests
- API check
- performance
- security
- replay

Evidence compiler automatically generates those verification steps.
Hermes never invents verification.

NOTE: Evidence collection is an axiomatic action that does not require evidence.
This avoids infinite regress (evidence for evidence).
Evidence collection is a privileged layer that is exempt from Law 8.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Set
from datetime import datetime, timezone
from enum import Enum
import json
import uuid
from pathlib import Path


class EvidenceType(Enum):
    """Types of evidence."""
    UNIT_TEST = "unit_test"
    INTEGRATION_TEST = "integration_test"
    API_TEST = "api_test"
    PERFORMANCE_TEST = "performance_test"
    SECURITY_TEST = "security_test"
    REPLAY_TEST = "replay_test"
    CODE_COVERAGE = "code_coverage"
    STATIC_ANALYSIS = "static_analysis"
    TYPE_CHECKING = "type_checking"
    FORMATTING_CHECK = "formatting_check"
    LOG_ANALYSIS = "log_analysis"
    ARTIFACT_VERIFICATION = "artifact_verification"
    SCHEMA_VALIDATION = "schema_validation"
    SIGNATURE_VERIFICATION = "signature_verification"


class EvidencePriority(Enum):
    """Priority of evidence collection."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class EvidenceRequirement:
    """A requirement for evidence collection."""
    requirement_id: str
    evidence_type: EvidenceType
    description: str
    source_artifact_id: Optional[str]
    target_artifact_id: Optional[str]
    verification_method: str
    success_criteria: str
    priority: EvidencePriority
    estimated_duration_seconds: int
    dependencies: List[str]  # Other evidence requirements this depends on
    metadata: Dict[str, Any]


@dataclass
class EvidencePlan:
    """
    Evidence plan generated by Evidence Compiler.
    
    Contains all evidence requirements for a mission.
    """
    plan_id: str
    mission_id: str
    generated_at: str
    generated_by: str
    requirements: List[EvidenceRequirement]
    execution_order: List[str]  # Order of requirement IDs
    total_estimated_duration_seconds: int
    critical_requirements: List[str]
    metadata: Dict[str, Any]
    
    def get_critical_path(self) -> List[str]:
        """Get critical path requirements."""
        return self.critical_requirements
    
    def get_requirements_by_priority(self, priority: EvidencePriority) -> List[EvidenceRequirement]:
        """Get requirements by priority."""
        return [req for req in self.requirements if req.priority == priority]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "plan_id": self.plan_id,
            "mission_id": self.mission_id,
            "generated_at": self.generated_at,
            "generated_by": self.generated_by,
            "requirements": [
                {
                    "requirement_id": req.requirement_id,
                    "evidence_type": req.evidence_type.value,
                    "description": req.description,
                    "source_artifact_id": req.source_artifact_id,
                    "target_artifact_id": req.target_artifact_id,
                    "verification_method": req.verification_method,
                    "success_criteria": req.success_criteria,
                    "priority": req.priority.value,
                    "estimated_duration_seconds": req.estimated_duration_seconds,
                    "dependencies": req.dependencies,
                    "metadata": req.metadata
                }
                for req in self.requirements
            ],
            "execution_order": self.execution_order,
            "total_estimated_duration_seconds": self.total_estimated_duration_seconds,
            "critical_requirements": self.critical_requirements,
            "metadata": self.metadata
        }


class EvidenceCompiler:
    """
    Evidence Compiler - Generates evidence plans from missions.
    
    Input: Mission
    Output: Evidence Plan
    
    Automatically generates verification steps based on mission characteristics.
    Hermes never invents verification.
    """
    
    def __init__(self):
        self._compiler_id = "evidence_compiler_v1"
    
    def compile(
        self,
        mission_id: str,
        mission_type: str,
        artifacts_produced: List[str],
        artifacts_consumed: List[str],
        capabilities_used: List[str],
        context: Dict[str, Any]
    ) -> EvidencePlan:
        """
        Compile evidence plan from mission.
        
        Args:
            mission_id: Mission ID
            mission_type: Type of mission
            artifacts_produced: Artifacts produced by mission
            artifacts_consumed: Artifacts consumed by mission
            capabilities_used: Capabilities used by mission
            context: Additional context
        
        Returns:
            EvidencePlan
        """
        requirements = []
        
        # Generate requirements based on mission characteristics
        requirements.extend(self._generate_code_requirements(mission_type, artifacts_produced))
        requirements.extend(self._generate_test_requirements(mission_type, artifacts_produced))
        requirements.extend(self._generate_security_requirements(capabilities_used))
        requirements.extend(self._generate_performance_requirements(mission_type))
        requirements.extend(self._generate_replay_requirements(mission_type))
        requirements.extend(self._generate_artifact_requirements(artifacts_produced))
        
        # Calculate execution order (topological sort)
        execution_order = self._calculate_execution_order(requirements)
        
        # Calculate total duration
        total_duration = sum(req.estimated_duration_seconds for req in requirements)
        
        # Identify critical requirements
        critical_requirements = [
            req.requirement_id for req in requirements
            if req.priority == EvidencePriority.CRITICAL
        ]
        
        return EvidencePlan(
            plan_id=str(uuid.uuid4()),
            mission_id=mission_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            generated_by=self._compiler_id,
            requirements=requirements,
            execution_order=execution_order,
            total_estimated_duration_seconds=total_duration,
            critical_requirements=critical_requirements,
            metadata={
                "mission_type": mission_type,
                "artifacts_produced": len(artifacts_produced),
                "artifacts_consumed": len(artifacts_consumed),
                "capabilities_used": len(capabilities_used)
            }
        )
    
    def _generate_code_requirements(
        self,
        mission_type: str,
        artifacts_produced: List[str]
    ) -> List[EvidenceRequirement]:
        """Generate code-related evidence requirements."""
        requirements = []
        
        # Static analysis
        if any(artifact.endswith(".py") for artifact in artifacts_produced):
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_static_{uuid.uuid4()}",
                evidence_type=EvidenceType.STATIC_ANALYSIS,
                description="Run static analysis on Python code",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="flake8",
                success_criteria="no_errors_or_warnings",
                priority=EvidencePriority.HIGH,
                estimated_duration_seconds=30,
                dependencies=[],
                metadata={"tool": "flake8"}
            ))
        
        # Type checking
        if any(artifact.endswith(".py") for artifact in artifacts_produced):
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_type_{uuid.uuid4()}",
                evidence_type=EvidenceType.TYPE_CHECKING,
                description="Run type checking on Python code",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="mypy",
                success_criteria="no_type_errors",
                priority=EvidencePriority.MEDIUM,
                estimated_duration_seconds=45,
                dependencies=[],
                metadata={"tool": "mypy"}
            ))
        
        # Formatting check
        if any(artifact.endswith(".py") for artifact in artifacts_produced):
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_format_{uuid.uuid4()}",
                evidence_type=EvidenceType.FORMATTING_CHECK,
                description="Check code formatting",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="black --check",
                success_criteria="no_formatting_issues",
                priority=EvidencePriority.MEDIUM,
                estimated_duration_seconds=15,
                dependencies=[],
                metadata={"tool": "black"}
            ))
        
        return requirements
    
    def _generate_test_requirements(
        self,
        mission_type: str,
        artifacts_produced: List[str]
    ) -> List[EvidenceRequirement]:
        """Generate test-related evidence requirements."""
        requirements = []
        
        # Unit tests
        if "code" in mission_type.lower():
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_unit_{uuid.uuid4()}",
                evidence_type=EvidenceType.UNIT_TEST,
                description="Run unit tests",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="pytest",
                success_criteria="all_tests_pass",
                priority=EvidencePriority.CRITICAL,
                estimated_duration_seconds=60,
                dependencies=[],
                metadata={"tool": "pytest"}
            ))
        
        # Integration tests
        if "deploy" in mission_type.lower() or "integration" in mission_type.lower():
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_integration_{uuid.uuid4()}",
                evidence_type=EvidenceType.INTEGRATION_TEST,
                description="Run integration tests",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="pytest integration/",
                success_criteria="all_tests_pass",
                priority=EvidencePriority.CRITICAL,
                estimated_duration_seconds=120,
                dependencies=[],
                metadata={"tool": "pytest"}
            ))
        
        # API tests
        if "api" in mission_type.lower() or "service" in mission_type.lower():
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_api_{uuid.uuid4()}",
                evidence_type=EvidenceType.API_TEST,
                description="Run API tests",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="pytest api/",
                success_criteria="all_endpoints_respond_correctly",
                priority=EvidencePriority.HIGH,
                estimated_duration_seconds=90,
                dependencies=[],
                metadata={"tool": "pytest"}
            ))
        
        return requirements
    
    def _generate_security_requirements(
        self,
        capabilities_used: List[str]
    ) -> List[EvidenceRequirement]:
        """Generate security-related evidence requirements."""
        requirements = []
        
        # Security scan if network capabilities used
        if any("network" in cap or "http" in cap for cap in capabilities_used):
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_security_{uuid.uuid4()}",
                evidence_type=EvidenceType.SECURITY_TEST,
                description="Run security scan",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="bandit",
                success_criteria="no_security_issues",
                priority=EvidencePriority.CRITICAL,
                estimated_duration_seconds=60,
                dependencies=[],
                metadata={"tool": "bandit"}
            ))
        
        return requirements
    
    def _generate_performance_requirements(
        self,
        mission_type: str
    ) -> List[EvidenceRequirement]:
        """Generate performance-related evidence requirements."""
        requirements = []
        
        # Performance test for production deployments
        if "deploy" in mission_type.lower() or "production" in mission_type.lower():
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_perf_{uuid.uuid4()}",
                evidence_type=EvidenceType.PERFORMANCE_TEST,
                description="Run performance tests",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="locust",
                success_criteria="response_time_below_threshold",
                priority=EvidencePriority.HIGH,
                estimated_duration_seconds=180,
                dependencies=[],
                metadata={"tool": "locust"}
            ))
        
        return requirements
    
    def _generate_replay_requirements(
        self,
        mission_type: str
    ) -> List[EvidenceRequirement]:
        """Generate replay-related evidence requirements."""
        requirements = []
        
        # Replay test for critical missions
        if "critical" in mission_type.lower() or "production" in mission_type.lower():
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_replay_{uuid.uuid4()}",
                evidence_type=EvidenceType.REPLAY_TEST,
                description="Run replay test",
                source_artifact_id=None,
                target_artifact_id=None,
                verification_method="event_replay",
                success_criteria="replay_produces_same_output",
                priority=EvidencePriority.HIGH,
                estimated_duration_seconds=120,
                dependencies=[],
                metadata={"method": "event_replay"}
            ))
        
        return requirements
    
    def _generate_artifact_requirements(
        self,
        artifacts_produced: List[str]
    ) -> List[EvidenceRequirement]:
        """Generate artifact-related evidence requirements."""
        requirements = []
        
        # Artifact verification for all produced artifacts
        for artifact in artifacts_produced:
            requirements.append(EvidenceRequirement(
                requirement_id=f"req_artifact_{uuid.uuid4()}",
                evidence_type=EvidenceType.ARTIFACT_VERIFICATION,
                description=f"Verify artifact {artifact}",
                source_artifact_id=None,
                target_artifact_id=artifact,
                verification_method="hash_verification",
                success_criteria="hash_matches_expected",
                priority=EvidencePriority.HIGH,
                estimated_duration_seconds=10,
                dependencies=[],
                metadata={"artifact": artifact}
            ))
        
        return requirements
    
    def _calculate_execution_order(self, requirements: List[EvidenceRequirement]) -> List[str]:
        """Calculate execution order using topological sort."""
        # Build dependency graph
        req_map = {req.requirement_id: req for req in requirements}
        in_degree = {req.requirement_id: len(req.dependencies) for req in requirements}
        
        # Start with nodes that have no dependencies
        queue = [req_id for req_id, degree in in_degree.items() if degree == 0]
        execution_order = []
        
        while queue:
            req_id = queue.pop(0)
            execution_order.append(req_id)
            
            # Find dependents
            for req in requirements:
                if req_id in req.dependencies:
                    in_degree[req.requirement_id] -= 1
                    if in_degree[req.requirement_id] == 0:
                        queue.append(req.requirement_id)
        
        # Add any remaining nodes (in case of cycles)
        for req_id in in_degree:
            if req_id not in execution_order:
                execution_order.append(req_id)
        
        return execution_order


class EvidenceExecutor:
    """
    Executes evidence plans.
    
    Collects evidence according to the plan.
    """
    
    def __init__(self, evidence_compiler: EvidenceCompiler):
        self.evidence_compiler = evidence_compiler
    
    async def execute_plan(self, plan: EvidencePlan) -> Dict[str, Any]:
        """
        Execute an evidence plan.
        
        Args:
            plan: Evidence plan to execute
        
        Returns:
            Execution results
        """
        results = {}
        
        for req_id in plan.execution_order:
            requirement = next(r for r in plan.requirements if r.requirement_id == req_id)
            
            try:
                result = await self._execute_requirement(requirement)
                results[req_id] = {
                    "success": True,
                    "result": result
                }
            except Exception as e:
                results[req_id] = {
                    "success": False,
                    "error": str(e)
                }
        
        return {
            "plan_id": plan.plan_id,
            "mission_id": plan.mission_id,
            "results": results,
            "total_requirements": len(plan.requirements),
            "successful": sum(1 for r in results.values() if r["success"]),
            "failed": sum(1 for r in results.values() if not r["success"])
        }
    
    async def _execute_requirement(self, requirement: EvidenceRequirement) -> Dict[str, Any]:
        """Execute a single evidence requirement."""
        # This is a placeholder - in production, this would call actual verification tools
        await asyncio.sleep(0.1)  # Simulate execution
        
        return {
            "requirement_id": requirement.requirement_id,
            "evidence_type": requirement.evidence_type.value,
            "verification_method": requirement.verification_method,
            "executed_at": datetime.now(timezone.utc).isoformat(),
            "evidence_collected": True
        }


# NOTE: Singleton pattern removed for determinism and testability.
# Use dependency injection instead.
# _evidence_compiler = EvidenceCompiler()
# _evidence_executor = EvidenceExecutor(_evidence_compiler)


def create_evidence_compiler() -> EvidenceCompiler:
    """Create a new evidence compiler instance."""
    return EvidenceCompiler()


def create_evidence_executor(evidence_compiler: EvidenceCompiler) -> EvidenceExecutor:
    """Create a new evidence executor instance."""
    return EvidenceExecutor(evidence_compiler)
